// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemasCP.Data;

#nullable disable

namespace SistemasCP.Migrations
{
    [DbContext(typeof(SistemasCPContext))]
    [Migration("20220706205600_BancoCompleto")]
    partial class BancoCompleto
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SistemasCP.Models.CriminalCodes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Penalty")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PrisionTime")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CriminalCode");
                });

            modelBuilder.Entity("SistemasCP.Models.status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CriminalCodesId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CriminalCodesId");

                    b.ToTable("status");
                });

            modelBuilder.Entity("SistemasCP.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.Property<string>("password")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("SistemasCP.Models.CriminalCodes", b =>
                {
                    b.HasOne("SistemasCP.Models.User", "User")
                        .WithMany("CriminalCodes")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SistemasCP.Models.status", b =>
                {
                    b.HasOne("SistemasCP.Models.CriminalCodes", "CriminalCodes")
                        .WithMany("StatusId")
                        .HasForeignKey("CriminalCodesId");

                    b.Navigation("CriminalCodes");
                });

            modelBuilder.Entity("SistemasCP.Models.CriminalCodes", b =>
                {
                    b.Navigation("StatusId");
                });

            modelBuilder.Entity("SistemasCP.Models.User", b =>
                {
                    b.Navigation("CriminalCodes");
                });
#pragma warning restore 612, 618
        }
    }
}
